//雷达图标
let optionspic = {
    canvasId:'chartFunnel',
    type:'funnel',
    title:{
        text:'漏斗图测试',
        position:'top',
        fillStyle:'#222'
    },
    legend:{
        align:'left'
    },
    grid:{
        top:80,
        right:14,
        bottom:80,
        left:80
    },
    radius:100,
    reverse:true,
    series:[
        {
            data:[
                {value:30,name:'展现'},
                {value:80,name:'点击',fillStyle:'#000'},
                {value:60,name:'访问'},
                {value:80,name:'咨询'},
                {value:100,name:'订单'}
            ],
        },
    ],
}
// return
let chartfunnel = new MbChart(optionspic)

setTimeout(()=>{
    // return
    chartfunnel.updata({
        series:[
            {
                data:[
                    {value:100,name:'展现'},
                    {value:60,name:'点击'},
                    {value:50,name:'访问'},
                    {value:40,name:'咨询'},
                    {value:50,name:'订单'}
                ],
            },
        ],
    })
},2000)

setTimeout(()=>{
    // return
    chartfunnel.drawCanvas({
        type:'funnel',
        title:{
            text:'漏斗图嗯测试',
            position:'bottom',
            fillStyle:'#222'
        },
        legend:{
            align:'left'
        },
        grid:{
            top:60,
            right:14,
            bottom:80,
            left:80
        },
        radius:80,
        reverse:true,
        series:[
            {
                data:[
                    {value:100,name:'展现'},
                    {value:80,name:'点击'},
                    {value:60,name:'访问'},
                    {value:40,name:'咨询'},
                    {value:20,name:'订单'}
                ],
            },
        ],
    })
},4000)